### ISSUE TITLE
JS error on "formattedChange"

### ISSUE THREAD

**Issue by nsapovits** [toddwschneider/stocks#11]
For the last week or two, I've noticed that the page doesn't fully load all values.  It fails on different stocks at different times depending on what stocks I am listing.  I am getting these errors in the browser console:

```
Uncaught (in promise) TypeError: Cannot read property 'toLocaleString' of null
    at stocks.html:171
    at Array.forEach (<anonymous>)
    at stocks.html:166
```

<img width="663" alt="Screen Shot 2019-07-23 at 11 33 24 AM" src="https://user-images.githubusercontent.com/11023396/61725391-b737ab80-ad3d-11e9-9d6f-7b68f7ce80fa.png">

**Comment by toddwschneider** [comment]
Hi @nsapovits, thanks for reporting. I've seen the same thing anecdotally in my own version. I *think* this PR that I just put in fixes it: https://github.com/toddwschneider/stocks/pull/12

But I can't confirm yet because right now the IEX API is returning all values for me. I'll check in tomorrow to make sure it behaves correctly when `quote.change` isn't available, and if so I'll close this issue. Thanks

**Comment by toddwschneider** [comment]
I believe this is fixed by a combination of https://github.com/toddwschneider/stocks/pull/12 and https://github.com/toddwschneider/stocks/commit/f3f7e22d5b61e6a5b09435e7ea391f1e274989c1

I'm closing the issue, but please let me know if you see any more broken behavior

**Comment by nsapovits** [comment]
Thanks Todd, it looks like the latest commit has resolved it.  Appreciate the quick response!
