### ISSUE TITLE
Quotes Not Pulling

### ISSUE THREAD

**Issue by littlebuck17** [toddwschneider/stocks#15]
Did something change from IEX? The demo website doesn't seem to be pulling any quotes.

**Comment by toddwschneider** [comment]
@littlebuck17 I think the token on the public version has maybe hit its free quota for the month

If you sign up for your own token at https://iexcloud.io/ and update the `const API_TOKEN = 'YOUR_TOKEN_HERE'` line, then it should work. Can you give that a try?

**Comment by toddwschneider** [comment]
@littlebuck17 the demo site is working again now that it's the first of the month and the free token quota has been reset. Presumably it might run out again sometime during the month, but I think this confirms my suspicion that the reason was that the free token had hit its limit

I'm going to close this issue, lmk if anything else. Thanks
