### ISSUE TITLE
No longer auto refresh

### ISSUE THREAD

**Issue by lliu5374** [toddwschneider/stocks#17]
Tried both chrome and safari.

**Comment by toddwschneider** [comment]
@lliu5374 can you be a bit more specific about the behavior you're seeing, and how it compares to what you expect to happen? Thanks

FWIW, this line of code dictates how often fresh quotes are pulled from IEX: https://github.com/toddwschneider/stocks/blob/master/index.html#L89

**Comment by lliu5374** [comment]
The source code is fairly clear about the refresh rate and “setInterval” call.
I am using your hosted app at https://toddwschneider.com/stocks. Maybe it’s not up-to-date?

Sorry for the confusion. I think it should be clear about what I meant by not auto refreshing. (fetched only once and the last updated timestamp stay the same forever)

Thank!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by toddwschneider** [comment]
@lliu5374 the copy hosted at https://toddwschneider.com/stocks/ has `REFRESH_SECONDS = 600`, i.e. it will only refresh every 10 minutes. I set it to a slow refresh because it was consistently running out of its free IEX monthly quota

If you want a version that refreshes more quickly, I recommend that you create your own IEX account, then make a copy of the page, set your IEX API token, and adjust the refresh to whatever you'd like

**Comment by lliu5374** [comment]
Ah, I see! It is no longer an issue than.
________________________________

**Comment by toddwschneider** [comment]
👍
